In [2]:
%matplotlib ipympl
# %matplotlib inline
import matplotlib.pyplot as plt
import tensorflow as tf
from utils import create_session_config
import tensorflow_probability as tp
import numpy as np
from models.utils import covariance,correlation_matrix,tf_cov,assert_cov_positive_definite,corr,print_tensor,print_tensors,constrain_cdf
from models.nn_pdf_common import transform_x,density_estimator,create_pdf_layer_mv,create_partially_monotone_dense_layer,create_monotone_dense_layer,create_positive_weights
from matplotlib import pyplot as plt
from scipy.stats import multivariate_normal
from flags import FLAGS
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import os
np.set_printoptions(threshold=np.inf)
from data.registry import uci_parkinsons_joint
from models.utils import get_train_inputs,get_eval_inputs
from models.rnade_deep import rnade_deep_model
from experiment.exporters import BestResultExporter

/home/pawel/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/pawel/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/pawel/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/pawel/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/pawel/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/pawel/tensorflow/lib/python3.5/importli

In [5]:
FLAGS.data_set="uci_parkinsons_joint"
data_loader = uci_parkinsons_joint() 

# tf.reset_default_graph()
# tf.set_random_seed(10)

# ds = get_train_inputs(data_loader, batch_size=200)
# iter = tf.data.Iterator.from_structure(ds.output_types,ds.output_shapes)
# training_init_op = iter.make_initializer(ds)
# batch=iter.get_next()

loaded data: uci_parkinsons_joint.npz


In [10]:
tf.reset_default_graph()
params = {}
params['arch']=[10,10,10]
params['batch_size'] = 200
params['k_mix']=3
params['num_ensambles']=2
params['learning_rate']=0.001
params['x_size'] = data_loader.train_x.shape[1]
params['y_size'] = data_loader.train_y.shape[1]
params['components_distribution'] = 'normal'

session_config=create_session_config()
run_config = tf.estimator.RunConfig(model_dir='/home/pawel/PycharmProjects/RM_labs/tmp4',
                                            save_summary_steps=FLAGS.save_summary_steps,
                                            save_checkpoints_steps=100,
                                            save_checkpoints_secs=None,
                                            log_step_count_steps=1000, keep_checkpoint_max=3,
                                            session_config=session_config,
                                            tf_random_seed=10)

estimator = tf.estimator.Estimator(config=run_config, model_fn=rnade_deep_model, params=params)


early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
                estimator,
                metric_name='loss',
                max_steps_without_decrease=FLAGS.max_steps_without_decrease,
                run_every_steps=100,
                run_every_secs=None)

hooks = [early_stopping_hook]
exporter = BestResultExporter()
eval_spec = tf.estimator.EvalSpec(
    input_fn=lambda: get_eval_inputs(data_loader, batch_size=params['batch_size']), steps=None, start_delay_secs=0,
    throttle_secs=FLAGS.eval_throttle_secs, hooks=hooks, exporters=exporter)
    
train_spec = tf.estimator.TrainSpec(input_fn=lambda: get_train_inputs(data_loader, batch_size=params['batch_size']), max_steps=None,
                                                hooks=hooks)
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)

# with tf.Session(config=tf.ConfigProto(gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.5))) as session:
#     session.run(tf.global_variables_initializer())
#     train_loop(30000, train_op)


INFO:tensorflow:Using config: {'_model_dir': '/home/pawel/PycharmProjects/RM_labs/tmp4', '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', '_tf_random_seed': 10, '_task_id': 0, '_save_checkpoints_secs': None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.035
}
, '_keep_checkpoint_max': 3, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5071a26668>, '_global_id_in_cluster': 0, '_save_checkpoints_steps': 100, '_master': '', '_num_ps_replicas': 0, '_save_summary_steps': 500, '_task_type': 'worker', '_protocol': None, '_eval_distribute': None, '_service': None, '_device_fn': None, '_log_step_count_steps': 1000, '_is_chief': True, '_train_distribute': None, '_num_worker_replicas': 1}
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: s

NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key dense_10/bias not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_BOOL], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[{{node save/RestoreV2/_301}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-864ec09585a7>", line 39, in <module>
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 343, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1129, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1163, in _train_model_default
    saving_listeners)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1371, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1215, in run
    run_metadata=run_metadata))
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 464, in after_run
    if self._save(run_context.session, global_step):
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 489, in _save
    if l.after_save(session, step):
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 497, in after_save
    self._evaluate(global_step_value)  # updates self.eval_result
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 517, in _evaluate
    self._evaluator.evaluate_and_export())
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 885, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 445, in evaluate
    return _evaluate()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 436, in _evaluate
    output_dir=self.eval_dir(name))
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1458, in _evaluate_run
    config=self._session_config)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/evaluation.py", line 209, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 832, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 555, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1018, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1023, in _create_session
    return self._sess_creator.create_session()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 712, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 474, in create_session
    self._scaffold.finalize()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 862, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1078, in __init__
    self.build()
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1090, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1127, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 459, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 838, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3260, in create_op
    op_def=op_def)
  File "/home/pawel/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key dense_10/bias not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_BOOL], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[{{node save/RestoreV2/_301}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


In [3]:
input=tf.constant([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],dtype=tf.float32)
output=tf.constant([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],dtype=tf.float32)
D=7
idx_sampler = tp.distributions.Categorical(probs=np.ones(D)/D, allow_nan_stats=False)
idx = idx_sampler.sample()
ordering = tf.random_shuffle(tf.range(0, D))
mask_idx = tf.slice(ordering, [idx], [-1])
mask = tf.where(tf.reduce_any(tf.equal(tf.reshape(tf.range(0, D),[-1,1]),mask_idx), axis=1), x=tf.zeros(D, dtype=tf.float32), y=tf.ones(D, dtype=tf.float32))
mask_matrix=tf.diag(mask)
input = tf.concat([tf.tile(tf.expand_dims(mask,0),[input.shape[0].value,1]),tf.matmul(input, mask_matrix)], axis=1) 

with tf.Session(config=tf.ConfigProto(gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.5))) as session:
    session.run(tf.global_variables_initializer())
    idx_,ordering_,mask_,input_,output_,mask_matrix_ = session.run([idx,ordering,mask,input,output,mask_matrix])
    
    print("index: ",idx_)
    print("ordering: ",ordering_)
    
    print("masked input\n", input_)
    print("masked output\n", output_)

index:  6
ordering:  [6 1 5 0 4 2 3]
masked input
 [[ 1.  1.  1.  0.  1.  1.  1.  1.  2.  3.  0.  5.  6.  7.]
 [ 1.  1.  1.  0.  1.  1.  1.  8.  9. 10.  0. 12. 13. 14.]]
masked output
 [[ 1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14.]]
